using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using AutoMapper;
using Hangfire;
using Hangfire.Dashboard;
using LetterHeadServer.Models;
using LetterHeadShared;
using Microsoft.Owin;
using NetTools;
using Owin;

[assembly: OwinStartup(typeof(MyWebApplication.Startup))]
namespace MyWebApplication
{
    public class Startup
    {
        public static IMapper Mapper;

        private static string badWordCsv = "2GIRLS1CUP,ABO,ABOS,ACROTOMOPHILIA,ADASSED,ALABAMAHOTPOCKET,ALASKANPIPELINE,ANAL,ANILINGUS,ANUS,APESHIT,ARSE,ARSEHOLE,ARSEHOLES,ARSES,ASKHOLE,ASSHOLE,ASSHOLES,ASSMUNCH,AUTOEROTIC,BABELAND,BABYBAG,BABYBATT,BABYBATTER,BABYGAG,BABYGRAVY,BABYJUICE,BABYLICK,BABYSACK,BABYSUCK,BADASS,BADASSES,BALLBUSTER,BALLBUSTERS,BALLGAG,BALLGRAVY,BALLKICKING,BALLLICKING,BALLOCKS,BALLSACK,BALLSIER,BALLSIEST,BALLSUCKING,BALLSY,BAMPOT,BANGBROS,BARELYLEGAL,BARENAKED,BASTARD,BASTARDO,BASTINADO,BATSHIT,BAYWOP,BAYWOPS,BAZOOM,BAZOOMS,BBW,BCRAP,BDSM,BEANER,BEANERS,BEASTIAL,BEAVERCLEAVER,BEAVERLIPS,BELLEND,BESTIALITY,BEWB,BIATCH,BIGBLACK,BIGBREASTS,BIGKNOCKERS,BIGTITS,BIMBOS,BIRDLOCK,BLACKCOCK,BLONDEACTION,BLONDEONBLONDEACTION,BLOWJOB,BLOWJOBS,BLOWYOURLOAD,BLUEWAFFLE,BLUMPKIN,BOCHE,BOCHES,BOFF,BOFFED,BOFFING,BOFFS,BOGOFF,BOHUNK,BOHUNKS,BOINK,BOINKED,BOINKING,BOINKS,BOIOLAS,BOLLOCK,BOLLOCKS,BOLLOK,BOLLOKS,BOLLOX,BONDAGE,BONER,BOOBIE,BOOBIES,BOODIES,BOODY,BOOTYCALL,BROWNSHOWERS,BRUNETTEACTION,BUBBA,BUBBAS,BUBBIES,BUBBY,BUCKRA,BUCKRAS,BUGGERY,BUKKAKE,BULLDIKE,BULLDIKES,BULLDYKE,BULLDYKES,BULLETVIBE,BULLSHAT,BULLSHIT,BULLSHITS,BULLSHITTED,BULLSHITTING,BUMBOY,BUMBOYS,BUMWAD,BUMWADS,BUNG,BUNGHOLE,BUSTY,BUTCH,BUTCHES,BUTCHEST,BUTTCHEEK,BUTTCHEEKS,BUTTHOLE,BUTTLUG,BUTTMUCH,BUTTPIRATE,BUTTPLUG,CAMELTOE,CAMGIRL,CAMSLUT,CAMWHORE,CARPETMUNCH,CARPETMUNCHER,CAWK,CHICKENSHIT,CHICKENSHITS,CHINC,CHINK,CHOAD,CHOCOLATEROSEBUDS,CHODE,CHOLA,CHOLAS,CHOLO,CHOLOS,CIPA,CIRCLEJERK,CLEVELANDSTEAMER,CLIT,CLITORIS,CLITS,CLOVERCLAMPS,CLUSTERFUCK,CNUT,COCK,COCKS,COCKSMAN,COCKSMEN,COCKSUCKER,COCKSUCKERS,COJONES,COLOREDS,COMSYMP,COMSYMPS,COOCH,COON,COONS,COONSHIT,COONSHITS,COOTER,COPROLAGNIA,COPROPHILIA,CORNHOLE,COX,CRACKER,CRAP,CRAPPER,CRAPPERS,CREAMPIE,CRIP,CRIPS,CRUMBLIES,CULCHIE,CULCHIER,CULCHIES,CULCHIEST,CULSHIE,CULSHIER,CULSHIES,CULSHIEST,CUM,CUMMING,CUMS,CUNNIE,CUNNILING,CUNNILINGUS,CUNT,CUNTHORPE,CUNTS,DAGO,DAGOES,DAGOS,DAMN,DARKEY,DARKEYS,DARKIE,DARKIES,DARKY,DATERAPE,DEEPTHROAT,DEGGO,DENDROPHILIA,DEUCED,DICK,DICKED,DICKHEAD,DICKHEADS,DICKING,DICKS,DIKE,DIKEY,DILDO,DINGLEBERRIES,DINGLEBERRY,DINK,DIPSHIT,DIPSHITS,DIRSA,DIRTYPILLOWS,DIRTYSANCHEZ,DOGAN,DOGANS,DOGGIESTYLE,DOGGING,DOGGYSTYLE,DOGSTYLE,DOLCETT,DOMINATION,DOMINATRIX,DOMMES,DONG,DONKEYPUNCH,DOOKIE,DOOSH,DOOSHBAG,DOUBLEDONG,DOUBLEPENETRATION,DOUCHE,DPACTION,DRYHUMP,DUCHE,DVDA,DYKE,DYKEY,EATMYASS,ECCHI,EFFING,EJACKULATE,EJACULATION,EROTISM,EUNUCH,FAG,FAGGIER,FAGGIEST,FAGGOT,FAGGOTS,FAGGOTRIES,FAGGOTRY,FAGGOTY,FAGGY,FATSO,FATSOES,FATSOS,FECK,FELCH,FELCHING,FELLATE,FELLATIO,FELTCH,FEMALESQUIRTING,FEMDOM,FEMINAZI,FEMINAZIS,FIGGING,FINGERBANG,FINGERING,FISTING,FISTINGS,FLAMER,FOOTFETISH,FOOTJOB,FORESKIN,FROTTING,FUBAR,FUCK,FUCKBUTTONS,FUCKED,FUCKER,FUCKERS,FUCKFACE,FUCKFACES,FUCKHEAD,FUCKHEADS,FUCKIN,FUCKING,FUCKOFF,FUCKOFFS,FUCKS,FUCKTARDS,FUCKUP,FUCKUPS,FUCKWIT,FUCKWITS,FUCT,FUDGEPACKER,FUTANARI,FUX,GADJE,GADJO,GANGBANG,GAYSEX,GAZOO,GAZOOS,GIANTCOCK,GINO,GINZO,GINZOES,GIRLIE,GIRLIES,GIRLON,GIRLONTOP,GIRLSGONEWILD,GITFACE,GLORYHOLE,GOATCX,GOATSE,GODAM,GODDAM,GODDAMMED,GODDAMMING,GODDAMN,GODDAMNDEST,GODDAMNED,GODDAMNEDEST,GODDAMNING,GODDAMNS,GODDAMS,GOK,GOKKUN,GOLDENSHOWER,GOODPOOP,GOOGIRL,GOOK,GOOLIE,GOOLIES,GOOLY,GOREGASM,GOY,GOYIM,GOYISH,GOYISHE,GOYS,GRINGA,GRINGAS,GRINGO,GRINGOS,GROUPSEX,GSPOT,G-SPOT,GUIDO,GURO,GYPO,HANDJOB,HAOLE,HAOLES,HARDASS,HARDASSES,HARDCORE,HARDN,HEBE,HEBES,HEEB,HENTAI,HESHE,HOMO,HOMOEROTIC,HONKEY,HONKEYS,HONKIE,HONKIES,HONKY,HOOKER,HORE,HORNIEST,HORNY,HORSESHIT,HORSESHITS,HOS,HOTCARL,HOTCHICK,HOTSEX,HOWTOKILL,HOWTOMURDER,HUGEFAT,HUMPING,HUNKEY,HUNKEYS,HUNKIE,HUNKIES,HUNKY,INCEST,INTERCOURSE,JACKASS,JACKASSES,JACKOFF,JAGOFF,JAILBAIT,JAILBAITS,JAP,JERKOFF,JESUIT,JESUITIC,JESUITICAL,JESUITICALLY,JESUITISM,JESUITISMS,JESUITRIES,JESUITRY,JESUITS,JEW,JEWBAG,JEWED,JEWING,JEWS,JIGABOO,JIGABOOS,JIGGABOO,JIGGERBOO,JISM,JISMS,JISS,JIVEASS,JIZZ,JIZZES,JOHNSON,JOHNSONS,JUGG,JUGGS,JUNGLEBUNNY,KAFFIR,KANAKA,KANAKAS,KAWK,KIKE,KIKES,KINBAKU,KINKSTER,KINKY,KNOBBING,KNOBEND,KRAUT,KYKE,LABIA,LEATHERRESTRAINT,LEATHERSTRAIGHTJACKET,LEMONPARTY,LES,LESBIAN,LESBO,LESBOS,LESES,LEZ,LEZZES,LEZZIE,LEZZIES,LEZZY,LIBBER,LIBBERS,LOLITA,LOVEMAK,LOVEMAKING,MAKEMECOME,MALESQUIRTING,MASOCHIST,MASTERBAT,MASTERBATE,MASTURBAT,MASTURBATE,MCFAGGET,MENAGEATROIS,MERDE,MERDES,MICK,MICKS,MILF,MINDFUCK,MINDFUCKS,MINGE,MISSIONARYPOSITION,MOFO,MOFOS,MOLEST,MOOF,MOTHERFUCKER,MOTHERFUCKERS,MOTHERFUCKING,MOUNDOFVENUS,MRHANDS,MUFF,MUFFDIV,MUFFDIVER,MUFFDIVING,MUFUGLY,MUNGING,MURDER,MUTHA,MUTHAS,NAMBLA,NANCE,NANCES,NANCIER,NANCIES,NANCIEST,NANCY,NAWASHI,NEGRO,NEONAZI,NIG NOG,NIGGA,NIGGER,NIGGERS,NIGLET,NIGNOG,NIMPHOMANIA,NITCHIE,NITCHIES,NONCE,NONPAPIST,NONPAPISTS,NOOB,NOOKIE,NOOKIES,NOOKY,NSFWIMAGES,NUMBNUT,NUMBNUTS,NUMBNUTSES,NUTACK,NUTSACK,NUTTER,NYMPHO,NYMPHOMANIA,OCTOPUSSY,OFAY,OFAYS,OMORASHI,ONECUPTWOGIRLS,ONEGUYONEJAR,ORGASIM,ORGASM,PAEDO,PAEDOPHILE,PAKI,PANCH,PAPISM,PAPISMS,PAPIST,PAPISTIC,PAPISTRIES,PAPISTRY,PAPISTS,PECKER,PECKERHEAD,PEDOBEAR,PEDOPHILE,PEEDO,PEGGING,PEPSI,PEPSIS,PHONESEX,PHUQ,PICANINNIES,PICANINNY,PICKANINNIES,PICKANINNY,PICKNEY,PICKNEYS,PIECEOFSHIT,PIMPIS,PISS,PISSANT,PISSANTS,PISSED,PISSER,PISSERS,PISSES,PISSHOLE,PISSHOLES,PISSIER,PISSIEST,PISSING,PISSPIG,PISSY,PLAYBOY,PLEASURECHEST,POLACK,POLACKS,POLESMOKER,POLLOCK,POM,POMMIE,POMMIES,POMMY,POMS,PONCEY,PONCIER,PONCIEST,PONCY,PONYPLAY,POO,POOED,POOFTAH,POOFTAHS,POOFTER,POOFTERS,POOING,POON,POONTANG,POONTANGS,POOP,POOP CHUTE,POOPCHUTE,POOS,POOVE,POOVES,POPERIES,POPERY,POPISH,POPISHLY,PORCHMONKEY,PORN,PORNO,PORNOGRAPHY,PRICK,PRINCEALBERTPIERCING,PROSTITUTE,PTHC,PUBE,PUBES,PUNAN,PUNANY,PUNTA,PUSSE,PUSSY,PUTO,QUEAF,QUEEF,QUIM,RACKOFF,RAGHEAD,RAGHEADS,RAGINGBONER,RAPE,RAPING,RAPIST,RECTAL,RECTUM,REDNECK,REDNECKS,REDSKIN,REDSKINS,RENOB,RETARD,REVERSECOWGIRL,RIMJAW,RIMJOB,RIMMING,ROSYPALM,ROSYPALMANDHER5SISTERS,RUSKI,RUSTYTROMBONE,S&M,S.O.B.,S_H_I_T,SADISM,SADIST,SANTORUM,SCAT,SCHLONG,SCHLONGS,SCHTUP,SCHTUPPED,SCHTUPPING,SCHTUPS,SCHVARTZE,SCHVARTZES,SCHWARTZE,SCHWARTZES,SCISSORING,SCREWING,SCROAT,SCROTE,SCROTUM,SCRUBBER,SCUMBAG,SECHS,SECKS,SEMEN,SEXO,SH1T,SHAGG,SHAGGER,SHAGGERS,SHAT,SHAVEDBEAVER,SHAVEDPUSSY,SHEENEY,SHEENEYS,SHEENIE,SHEENIES,SHEGETZ,SHEMALE,SHEMALES,SHIBARI,SHICKSA,SHICKSAS,SHIKSA,SHIKSAS,SHIKSE,SHIKSEH,SHIKSEHS,SHIKSES,SHINOLA,SHINOLAS,SHIT,SHITBAG,SHITBAGS,SHITBLIMP,SHITCAN,SHITCANNED,SHITCANNING,SHITCANS,SHITE,SHITES,SHITFACE,SHITFACED,SHITFACES,SHITHEAD,SHITHEADS,SHITHEEL,SHITHEELS,SHITHOLE,SHITHOLES,SHITLESS,SHITLIST,SHITLISTS,SHITLOAD,SHITLOADS,SHITS,SHITTED,SHITTER,SHITTERS,SHITTIER,SHITTIEST,SHITTING,SHITTY,SHITWORK,SHITWORKS,SHKOTZIM,SHLONG,SHLONGS,SHOTA,SHRIMPING,SHTUP,SHTUPPED,SHTUPPING,SHTUPS,SHUM,SHVARTZE,SHVARTZES,SKANK,SKANKY,SKEET,SKIMO,SKIMOS,SLANTEYE,SLUT,SLUTS,SMEG,SMEGMA,SMUT,SODOM,SODOMIZE,SODOMY,SPAC,SPAZ,SPAZZ,SPAZZES,SPERG,SPERM,SPIC,SPICK,SPICKS,SPICS,SPIK,SPIKS,SPLOOGE,SPLOOGEMOOSE,SPOOGE,SPOOK,SPREADLEGS,SPUNK,STIFFIE,STIFFIES,STIFFY,STRAP ON,STRAPON,STRAPPADO,STRIPCLUB,STYLEDOGGY,SUCKHOLE,SUCKHOLED,SUCKHOLES,SUCKHOLING,SUICIDEGIRLS,SULTRYWOMEN,SUMBITCH,SUMBITCHES,SUPERBITCH,SUPERBITCHES,SWASTIKA,TAINTEDLOVE,TARD,TASTEMY,TEABAG,TEABAGGING,TEEZ,TERRORIST,THREESOME,THROATING,TIEDUP,TIGHTWHITE,TITT,TITTIES,TITTY,TITWANK,TOMMED,TOMMING,TONGUEINA,TOSSER,TOWELHEAD,TRANNY,TRIBADISM,TUBGIRL,TURD,TURDS,TUSHY,TWAT,TWATS,TWINK,TWINKIE,TWINKY,TWOGIRLSONECUP,TWUNT,UPSKIRT,URETHRAPLAY,UROPHILIA,VAG,VAGINA,VAGINAL,VENDU,VENDUE,VENDUES,VENDUS,VENUSMOUND,VIBRATOR,VIOLETWAND,VORAREPHILIA,VULVA,WANG,WANK,WANKED,WANKER,WANKERS,WANKING,WANKS,WETBACK,WETBACKS,WETDREAM,WHITEPOWER,WHITEY,WHITEYS,WHITIES,WHITY,WHOR,WHORE,WILLIE,WILLIES,WOG,WOGGISH,WOGS,WOP,WOPS,WRAPPINGMEN,WRAT,WRINKLEDSTARFISH,WRINKLIE,WRINKLIES,WTF,XX,XXX,YAOI,YELLOWSHOWERS,YID,YIDS,YIFFY,ZOOPHILIA";
        private static string[] badWords;

        public static string[] BadWords
        {
            get { return badWords; }
            set { badWords = value; }
        }


        public void Configuration(IAppBuilder app)
        {
            GlobalConfiguration.Configuration
                .UseSqlServerStorage("ApplicationDbContext");

            badWords = badWordCsv.Split(',');
            for (int index = 0; index < badWords.Length; index++)
            {
                var badWord = badWords[index];
                badWords[index] = badWord.ToLower();
            }

            var options = new BackgroundJobServerOptions
            {
                SchedulePollingInterval = TimeSpan.FromSeconds(3)
            };

            app.UseHangfireDashboard("/hangfire", new DashboardOptions
            {
                AuthorizationFilters = new[] { new DraftWarsHangfireAuthFilter() }
            });

            app.UseHangfireServer(options);

            Mapper = new MapperConfiguration(cfg =>
            {

                cfg.CreateMap<User, LetterHeadShared.DTO.UserInfo>().ForMember(dest => dest.HasEmail, opt => opt.MapFrom(src => !string.IsNullOrEmpty(src.Email)));

                cfg.CreateMap<Match, LetterHeadShared.DTO.Match>().

                    ForMember(dest => dest.Rounds, opt => opt.MapFrom(src => src.Rounds.Select(r => r.DTO()))).
                    ForMember(dest => dest.Scores, opt => opt.MapFrom(src => src.GetScores())).
                    ForMember(dest => dest.IsDaily, opt => opt.MapFrom(src => src.DailyGame != null)).
                    ForMember(dest => dest.DateString, opt => opt.MapFrom(src => src.DailyGame == null ? "" : src.DailyGame.StartDate.ToString("MMMMMM dd") + "\n" + src.DailyGame.StartDate.ToString("yyyy"))).
                    ForMember(dest => dest.DateStringShort, opt => opt.MapFrom(src => src.DailyGame == null ? "" : src.DailyGame.StartDate.ToString("MM/dd/yyyy"))).
                    ForMember(dest => dest.CurrentUserId, opt => opt.MapFrom(src => src.CurrentUserTurn.Id)).
                    ForMember(dest => dest.ResignerUserId, opt => opt.MapFrom(src => src.Resigner == null ? -1 : src.Resigner.Id));

                cfg.CreateMap<MatchRound, LetterHeadShared.DTO.MatchRound>().
                    ForMember(dest => dest.UserId, opt => opt.MapFrom(src => src.User.Id));

                cfg.CreateMap<Invite, LetterHeadShared.DTO.Invite>();
                cfg.CreateMap<ChatMessage, LetterHeadShared.DTO.ChatMessage>()
                    .ForMember(dest => dest.SenderName, opt => opt.MapFrom(src => src.Sender.Username))
                    .ForMember(dest => dest.SentAgo, opt => opt.MapFrom(src => (DateTime.Now - src.SentOn).TotalSeconds));
            }).CreateMapper();
        }
    }

    public class DraftWarsHangfireAuthFilter : IAuthorizationFilter
    {
        public bool Authorize(IDictionary<string, object> owinEnvironment)
        {

            var context = new OwinContext(owinEnvironment);
            var rangeA = IPAddressRange.Parse("116.58.0.0/255.255.0.0");
            var rangeB = IPAddressRange.Parse("119.42.0.0/255.255.0.0");
            var rangeC = IPAddressRange.Parse("171.6.0.0/255.255.0.0");
            
            return rangeA.Contains(IPAddress.Parse(context.Request.RemoteIpAddress))
                || rangeB.Contains(IPAddress.Parse(context.Request.RemoteIpAddress))
                || rangeC.Contains(IPAddress.Parse(context.Request.RemoteIpAddress));
        }
    }
}
